all:
  hosts:
    kube-dev-node-1:
      ansible_host: 192.168.32.2
      ip: 192.168.32.2
      access_ip: 192.168.32.2
    kube-dev-node-2:
      ansible_host: 192.168.4.82
      ip: 192.168.4.82
      access_ip: 192.168.4.82
    kube-dev-node-3:
      ansible_host: 192.168.4.83
      ip: 192.168.4.83
      access_ip: 192.168.4.83
  children:
    kube_control_plane:
      hosts:
        kube-dev-node-1:
        kube-dev-node-2:
    kube_node:
      hosts:
        kube-dev-node-1:
        kube-dev-node-2:
        kube-dev-node-3:
    etcd:
      hosts:
        kube-dev-node-1:
        kube-dev-node-2:
        kube-dev-node-3:
    k8s_cluster:
      children:
        kube_control_plane:
        kube_node:
    calico_rr:
      hosts: {}